### ISSUE TITLE
go-lambda create stuck at exec format error

### ISSUE THREAD

**Issue by udhos** [xlab/go-lambda#3]
How do I get past this error?

System is: Linux deb 3.16.0-4-586 #1 Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) i686 GNU/Linux

```
lab@deb:~/go/bin$ ./go-lambda create --role arn:aws:iam::account-id:role/lambda_basic_execution handler github.com/xlab/go-lambda/example
exec format error
FATA[0000] Error response from daemon: Cannot start container 28255278a85d1739ae7880c5ed4f360ca2377334c0e116d93cf595714f24fdc9: [8] System error: exec format error
docker.go:94: exit status 1
lab@deb:~/go/bin$
```

**Comment by xlab** [comment]
Hi! Thanks for the report.

Firstly, I'd advise to use the `--verbose` flag so you can see what is actually going on and which commands are executed by this tool.

Normally go-lambda checks whether the environment is "native" using this function:

```
func isNative() bool {
    return runtime.GOOS == "linux" && runtime.GOARCH == "amd64"
}
```

So on `Linux x86_64` it will compile the app using your environment, otherwise it will pull a Docker image [go-lambda](https://hub.docker.com/r/xlab/go-lambda/) that is based on the official `golang:1.7-wheezy` image that has this version of Go installed: `ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz`

So you'll have to get x86_64 arch somehow, since you must compile your Go code for Amazon Lambda that is 64-bit only.

Cheers.
